language: ruby
rvm:
- 2.3.0
- 2.2
cache: bundler
addons:
  postgresql: '9.5'
before_script:
- cp config/database.yml.travis config/database.yml
script:
- bundle exec rake db:setup RAILS_ENV=test
- bundle exec rake db:test:prepare RAILS_ENV=test
- bundle exec rake db:fixtures:load RAILS_ENV=test
- bundle exec rake test RAILS_ENV=test
sudo: false
