# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ca1246f6357d8421ec22d63b1e04a001be9f56a2b11d9ea1e671264a09ef43cb1e5b0951b7e09ee31d8330dc47f202ee8ad195b5372049bf931141f701acd7f
  static_url: 'http://ace.uaf.edu'
  ckan_url: 'http://ace.gina.alaska.edu'
test:
  secret_key_base: 218fca4b33c0aa031dddb5aa1224651561b78bac32d1469b55dc1543bec4025827cc7e6420a88251f47d14109fbe7e2a81b71a02b4a517c781b22fcee489137c
  ckan_url: 'http://ace.gina.alaska.edu'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  static_url: 'http://ace.uaf.edu'
  ckan_url: 'http://catalog.ace.uaf.edu'
